### ISSUE TITLE
Cooler details elements

### ISSUE THREAD

**Issue by wavebeem** [wavebeem/wavebeem.com#106]
Use a custom triangle on the right?

```css
.hamburger summary {
  position: relative;
  background: var(--color-header-button);
  padding: 0.25rem 1rem;
  border-radius: 9999px;
  font-weight: 800;
  cursor: default;
  list-style-type: none;
}

.hamburger summary::after {
  content: "";
  display: inline-block;
/* HTML: <div class="triangle"></div> */
  width: 0.5em;
  aspect-ratio: 1/cos(30deg);
  clip-path: polygon(50% 100%,100% 0,0 0);
  background: currentColor;
  margin-left: 0.5rem;
  justify-content: center;
  align-items: center;
  vertical-align: middle;
/*   transition: rotate 100ms; */
}

.hamburger[open] summary::after {
  rotate: -0.5turn;
}
```
